### PR TITLE
added-dp-problems

### PR DESCRIPTION
**Pull request by Fabayu**
Addind common patterns questions on dp

### CODE REVIEW

**Comment by Fabayu** [comment]
Adding dp common pattern questions

**Comment by BhavyaT-135** [comment]
@Fabayu you're not supposed to add cpp files. Only python files are acceptable. Plus, I'd appreciate it if you don't delete previous files without asking and contribute one file or topic at a time😊

**Comment by Fabayu** [comment]
Sure since m beginner at contributing so doing some silly  mistakes 
Thanks for the guidance !!

**Comment by BeeBombshell** [comment]
Hey @Fabayu, closing this PR since it contains all the files in `.cpp`. You can create a fresh PR to add one topic at a time in Python language. No worries. 😄

**Comment by Fabayu** [comment]
I will appeal in the supreme court ..how can u close this ??😥😥😥😅

**Pull request closed without merging**
