### PR TITLE
sort-all-added

### PR DESCRIPTION
**Pull request by Fabayu**
Added all sorting algo with code in python

### CODE REVIEW

**Comment by Fabayu** [comment]
Added for review

**Review by BhavyaT-135 — CHANGES_REQUESTED** [review]
@Fabayu You've done a commendable job 💯 

However, would it be possible for you to break down the sorting algorithms and submit python files instead of the markdown file. That way you'll be able to complete PRs for the hacktoberfest as well. Everything else looks good. 😃

**Comment by Fabayu** [comment]
Thanks, ma'am !!
I m a complete beginner to open source so this is quite an achievement for me.
Sure I will try to submit python files .

**Comment by Fabayu** [comment]
Done with the required changes any more suggestions are welcomed 
thanks !!

**Comment by Fabayu** [comment]
pls review this for merge @BeeBombshell @BhavyaT-135 any more suggestions ??

**Review by BhavyaT-135 — APPROVED** [review]
LGTM!👍

**Pull request merged**
